### ISSUE TITLE
Add default PHPStorm configuration that can be imported so people can get started quickly

### ISSUE THREAD

**Issue by dsnopek** [panopoly/panopoly-sprint-kit#12]

**Comment by mglaman** [comment]
So I've got a base config setup, however getting the folder to recursively be copied over is having issues in provisioning. Synchronize module is barking at the connection, which I'm not sure how we can resolve within packer.io (versus Vagrant.)

I might just make a new role which runs after kit-ui to manually build out the folder. A new role because it'll be a lot of tasks, and easily replaced if we find a better way.

**Comment by dsnopek** [comment]
Or we could put it in a .tar.gz which gets copied to /usr/share/panopoly-kit/phpstorm-project.tar.gz and then the panopoly-kit script can extract it after it builds the Drupal root?

**Comment by mglaman** [comment]
So I think I'd like to have it run `local_action` and tar it on provision, then copy it over, and then untar it or something. Personal preference to not put archives in a git repo :) but also that way its easier to make edits and adjustments with less manual re-archiving
